# Generated by Django 5.0.1 on 2024-02-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_news_razor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Original_Rank', models.IntegerField()),
                ('New_Rank', models.IntegerField()),
                ('Change', models.IntegerField()),
                ('College', models.CharField(max_length=255)),
                ('Fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Faculty', models.CharField(max_length=255)),
                ('SS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FSR', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FQE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FRU', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PU', models.DecimalField(decimal_places=2, max_digits=10)),
                ('QP', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IPR', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FPPP', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GPH', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GUE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GMS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GPHD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('WD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ESCS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PCS', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PR', models.DecimalField(decimal_places=2, max_digits=10)),
                ('xx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Add_your_news',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
